import type { Partner } from '@/types/partner'

export const PARTNERS: Partner[] = [
  {
    slug: 'ad-surgical',
    name: 'AD Surgical',
    vendorName: 'AD Surgical',
    type: 'brand',
    isActive: true,
    description: 'Leading provider of surgical sutures, wound closure, and procedure kits.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/8c489793-5cbe-4f61-8fcd-19ba4119eec9',
      altText: 'AD Surgical logo',
      width: 200,
      height: 80,
    },
    intro: 'AD Surgical is a trusted name in surgical wound management, offering a comprehensive portfolio of sutures, wound closure strips, staples, and procedure kits designed for clinical precision and consistent outcomes.',
    productCategories: ['surgical', 'wound-closure', 'sutures', 'procedure-kits'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'surgical', title: 'Surgical Supplies' },
      { handle: 'wound-care', title: 'Wound Care' },
    ],
    seoTitle: 'AD Surgical Products | MDSupplies',
    seoDescription: 'Shop AD Surgical sutures, wound closure, and procedure kits at wholesale prices through MDSupplies.',
  },
  {
    slug: 'cordx',
    name: 'CorDx',
    vendorName: 'CorDx',
    type: 'brand',
    isActive: true,
    description: 'Advanced rapid diagnostic testing solutions for clinical and point-of-care settings.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/2ff04940-2487-4aa4-8daa-1f440301fc04',
      altText: 'CorDx logo',
      width: 200,
      height: 80,
    },
    intro: 'CorDx develops rapid diagnostic tests and point-of-care solutions trusted by clinics, urgent care centers, and public health agencies. Their portfolio spans infectious disease testing, flu panels, and molecular assays.',
    productCategories: ['diagnostics', 'rapid-tests', 'point-of-care'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'diagnostics', title: 'Diagnostics' },
      { handle: 'rapid-tests', title: 'Rapid Tests' },
    ],
    seoTitle: 'CorDx Rapid Diagnostic Products | MDSupplies',
    seoDescription: 'Shop CorDx rapid diagnostic testing solutions at wholesale prices through MDSupplies.',
  },
  {
    slug: 'dukal',
    name: 'Dukal',
    vendorName: 'Dukal',
    type: 'brand',
    isActive: true,
    description: 'High-quality disposable medical products for wound care, exam, and procedure use.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/0d3ad4a5-6272-46a4-8120-e7e86dee0773',
      altText: 'Dukal logo',
      width: 200,
      height: 80,
    },
    intro: 'Dukal Corporation manufactures high-quality disposable medical products including gauze sponges, wound dressings, exam gloves, and surgical drapes trusted by healthcare facilities across the United States.',
    productCategories: ['wound-care', 'surgical', 'exam-room', 'gauze'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'wound-care', title: 'Wound Care' },
      { handle: 'surgical', title: 'Surgical Supplies' },
      { handle: 'exam-room', title: 'Exam Room' },
    ],
    seoTitle: 'Dukal Medical Products | MDSupplies',
    seoDescription: 'Shop Dukal wound care, surgical, and disposable medical products at wholesale prices through MDSupplies.',
  },
  {
    slug: 'dynarex',
    name: 'Dynarex',
    vendorName: 'Dynarex',
    type: 'brand',
    isActive: true,
    description: 'Dependable general medical products trusted by healthcare providers nationwide.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/40c82316-c043-4b64-8be8-585ed3276f96',
      altText: 'Dynarex logo',
      width: 200,
      height: 80,
    },
    intro: 'Dynarex is one of the largest manufacturers of general medical products in the United States, offering thousands of SKUs across gloves, wound care, personal protective equipment, and exam room essentials.',
    productCategories: ['disposables', 'wound-care', 'ppe', 'exam-room'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'disposables', title: 'Disposables' },
      { handle: 'ppe', title: 'PPE' },
      { handle: 'wound-care', title: 'Wound Care' },
    ],
    seoTitle: 'Dynarex Medical Products | MDSupplies',
    seoDescription: 'Shop Dynarex gloves, wound care, and disposable medical supplies at wholesale prices through MDSupplies.',
  },
  {
    slug: 'drive-medical',
    name: 'Drive Medical',
    vendorName: 'Drive Medical',
    type: 'brand',
    isActive: true,
    description: 'Durable medical equipment and mobility solutions for healthcare.',
    logo: {
      url: 'https://placehold.co/200x80/e0e7ff/4338ca?text=Drive+Medical',
      altText: 'Drive Medical logo',
      width: 200,
      height: 80,
    },
    intro: 'Drive Medical designs and manufactures durable medical equipment trusted by healthcare facilities and home health providers worldwide, including wheelchairs, walkers, and patient aids.',
    productCategories: ['dme', 'mobility-aids', 'home-health'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'dme', title: 'Durable Medical Equipment' },
      { handle: 'mobility-aids', title: 'Mobility Aids' },
    ],
    seoTitle: 'Drive Medical Products | MDSupplies',
    seoDescription: 'Shop Drive Medical durable medical equipment and mobility aids at wholesale prices.',
  },
  {
    slug: 'kadara',
    name: 'Kadara',
    vendorName: 'Kadara',
    type: 'brand',
    isActive: true,
    description: 'Innovative medical supply solutions focused on quality and clinical performance.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/57a084ab-54d3-4aac-bbb6-2230b7945506',
      altText: 'Kadara logo',
      width: 200,
      height: 80,
    },
    intro: 'Kadara designs innovative medical supplies built for clinical performance and reliability. Their product line emphasizes quality manufacturing standards and consistent delivery for healthcare providers.',
    productCategories: ['medical-supplies', 'clinical-products'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'medical-supplies', title: 'Medical Supplies' },
    ],
    seoTitle: 'Kadara Medical Supply Products | MDSupplies',
    seoDescription: 'Shop Kadara innovative medical supply solutions at wholesale prices through MDSupplies.',
  },
  {
    slug: 'kemp-usa',
    name: 'Kemp USA',
    vendorName: 'Kemp USA',
    type: 'brand',
    isActive: true,
    description: 'Professional-grade medical equipment and emergency response supplies.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/4feee5b9-fc58-439f-9232-841240db91f2',
      altText: 'Kemp USA logo',
      width: 200,
      height: 80,
    },
    intro: 'Kemp USA manufactures professional-grade medical and emergency response equipment including stretchers, backboards, first aid kits, and AED supplies used by first responders and healthcare facilities.',
    productCategories: ['emergency', 'first-aid', 'stretchers', 'aed'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'emergency', title: 'Emergency Supplies' },
      { handle: 'first-aid', title: 'First Aid' },
    ],
    seoTitle: 'Kemp USA Emergency & Medical Equipment | MDSupplies',
    seoDescription: 'Shop Kemp USA medical equipment and emergency response supplies at wholesale prices through MDSupplies.',
  },
  {
    slug: 'graham-field',
    name: 'Graham Field',
    vendorName: 'Graham Field',
    type: 'brand',
    isActive: true,
    description: 'Comprehensive durable medical equipment and rehabilitation solutions.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/1a1a19d2-e56f-4f27-9b46-e2cc7fffc8df',
      altText: 'Graham Field logo',
      width: 200,
      height: 80,
    },
    intro: 'Graham Field Health Products is a leading manufacturer and distributor of durable medical equipment and rehabilitation products. Their brands—including Lumex and Everest & Jennings—serve patients from acute care to home health settings.',
    productCategories: ['dme', 'rehabilitation', 'patient-care', 'mobility-aids'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'dme', title: 'Durable Medical Equipment' },
      { handle: 'rehabilitation', title: 'Rehabilitation' },
    ],
    seoTitle: 'Graham Field Medical Products | MDSupplies',
    seoDescription: 'Shop Graham Field durable medical equipment and rehabilitation solutions at wholesale prices through MDSupplies.',
  },
  {
    slug: 'medline',
    name: 'Medline',
    vendorName: 'Medline',
    type: 'brand',
    isActive: true,
    description: 'One of the largest manufacturers and distributors of healthcare supplies in the US.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/9f893490-1d51-45bf-ba02-a012f9d5a8b3',
      altText: 'Medline logo',
      width: 200,
      height: 80,
    },
    intro: 'Medline Industries is one of the largest privately held manufacturers and distributors of healthcare products in the United States. With over 350,000 products across virtually every care setting, Medline partners with healthcare facilities to improve clinical and financial outcomes.',
    productCategories: ['gloves', 'wound-care', 'surgical', 'patient-care', 'ppe', 'disposables'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'gloves', title: 'Gloves' },
      { handle: 'wound-care', title: 'Wound Care' },
      { handle: 'surgical', title: 'Surgical Supplies' },
      { handle: 'ppe', title: 'PPE' },
    ],
    seoTitle: 'Medline Healthcare Products | MDSupplies',
    seoDescription: 'Shop Medline medical supplies, gloves, wound care, and more at wholesale prices through MDSupplies.',
  },
  {
    slug: 'systems',
    name: 'Systems',
    vendorName: 'Systems',
    type: 'brand',
    isActive: true,
    description: 'Integrated medical supply systems for streamlined clinical procurement.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/bd49eacf-6f92-4512-b5fd-c795d35acbd2',
      altText: 'Systems logo',
      width: 200,
      height: 80,
    },
    intro: 'Systems provides integrated medical supply solutions that streamline procurement and inventory management for healthcare facilities. Their systems approach simplifies ordering and reduces supply chain complexity.',
    productCategories: ['medical-supplies', 'procurement', 'clinical-systems'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'medical-supplies', title: 'Medical Supplies' },
    ],
    seoTitle: 'Systems Medical Supply Solutions | MDSupplies',
    seoDescription: 'Shop Systems integrated medical supply solutions at wholesale prices through MDSupplies.',
  },
  {
    slug: 'philip-scalice',
    name: 'Philip Scalice',
    vendorName: 'Philip Scalice',
    type: 'brand',
    isActive: true,
    description: 'Specialty medical supplies and instruments for clinical and surgical use.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/4f85d0fb-edfb-44c7-93d8-11f795a75e52',
      altText: 'Philip Scalice logo',
      width: 200,
      height: 80,
    },
    intro: 'Philip Scalice offers specialty medical supplies and instruments designed for clinical and surgical applications. Their product range supports precise procedural outcomes across multiple care disciplines.',
    productCategories: ['surgical', 'instruments', 'specialty-supplies'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'surgical', title: 'Surgical Supplies' },
      { handle: 'instruments', title: 'Medical Instruments' },
    ],
    seoTitle: 'Philip Scalice Specialty Medical Supplies | MDSupplies',
    seoDescription: 'Shop Philip Scalice specialty medical supplies and instruments at wholesale prices through MDSupplies.',
  },
  {
    slug: 'truecare',
    name: 'TrueCare',
    vendorName: 'TrueCare',
    type: 'brand',
    isActive: true,
    description: 'Patient-centered wound care and disposable medical supply solutions.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/35a25913-e45f-40fb-bed3-02bfccad6b4e',
      altText: 'TrueCare logo',
      width: 200,
      height: 80,
    },
    intro: 'TrueCare develops patient-centered wound care and disposable medical supplies that prioritize comfort and clinical effectiveness. Their products are designed for consistent performance in wound management and daily patient care.',
    productCategories: ['wound-care', 'disposables', 'patient-care'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'wound-care', title: 'Wound Care' },
      { handle: 'disposables', title: 'Disposables' },
    ],
    seoTitle: 'TrueCare Wound Care & Disposable Supplies | MDSupplies',
    seoDescription: 'Shop TrueCare wound care and disposable medical supply solutions at wholesale prices through MDSupplies.',
  },
  {
    slug: 'vive-health',
    name: 'Vive Health',
    vendorName: 'Vive Health',
    type: 'brand',
    isActive: true,
    description: 'Daily living aids, mobility equipment, and home health supplies.',
    logo: {
      url: 'https://www.figma.com/api/mcp/asset/0b4afb00-deb5-4dc9-8a3e-bef93ff6f60d',
      altText: 'Vive Health logo',
      width: 200,
      height: 80,
    },
    intro: 'Vive Health designs daily living aids, mobility equipment, and home health supplies that empower patients to live independently. Their accessible product line serves individuals recovering from injury or managing chronic conditions.',
    productCategories: ['dme', 'mobility-aids', 'daily-living', 'home-health'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'dme', title: 'Durable Medical Equipment' },
      { handle: 'mobility-aids', title: 'Mobility Aids' },
      { handle: 'home-health', title: 'Home Health' },
    ],
    seoTitle: 'Vive Health Home Health & Mobility Products | MDSupplies',
    seoDescription: 'Shop Vive Health daily living aids and mobility equipment at wholesale prices through MDSupplies.',
  },
  {
    slug: 'dawn-mist',
    name: 'Dawn Mist',
    vendorName: 'Dawn Mist',
    type: 'brand',
    isActive: true,
    description: 'Premium personal care and hygiene products for healthcare facilities.',
    logo: {
      url: 'https://placehold.co/200x80/e5eff7/0086b1?text=Dawn+Mist',
      altText: 'Dawn Mist logo',
      width: 200,
      height: 80,
    },
    intro: 'Dawn Mist is a leading brand of personal care products trusted by hospitals and long-term care facilities across North America.',
    productCategories: ['personal-care', 'hygiene', 'bath-supplies'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'personal-care', title: 'Personal Care' },
      { handle: 'hygiene', title: 'Hygiene Supplies' },
    ],
    seoTitle: 'Dawn Mist Products | MDSupplies',
    seoDescription: 'Browse Dawn Mist personal care and hygiene products available at wholesale prices through MDSupplies.',
  },
  {
    slug: 'lumex',
    name: 'Lumex',
    vendorName: 'Lumex',
    type: 'brand',
    isActive: true,
    description: 'Durable medical equipment and mobility aids for patient care.',
    logo: {
      url: 'https://placehold.co/200x80/f0fdf4/166534?text=Lumex',
      altText: 'Lumex logo',
      width: 200,
      height: 80,
    },
    intro: 'Lumex specializes in durable medical equipment including walkers, wheelchairs, and patient lifts used in home care and clinical settings.',
    productCategories: ['dme', 'mobility-aids', 'patient-lifts'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'dme', title: 'Durable Medical Equipment' },
      { handle: 'mobility-aids', title: 'Mobility Aids' },
    ],
  },
  {
    slug: 'dynao2',
    name: 'DynaO2',
    vendorName: 'DynaO2',
    type: 'brand',
    isActive: true,
    description: 'Respiratory therapy and oxygen delivery products for clinical use.',
    logo: {
      url: 'https://placehold.co/200x80/fef9c3/854d0e?text=DynaO2',
      altText: 'DynaO2 logo',
      width: 200,
      height: 80,
    },
    intro: 'DynaO2 manufactures respiratory therapy products including nasal cannulas, oxygen masks, and nebulizer kits for hospitals and home health agencies.',
    productCategories: ['respiratory', 'oxygen-therapy'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'respiratory', title: 'Respiratory Supplies' },
      { handle: 'oxygen-therapy', title: 'Oxygen Therapy' },
    ],
  },
]

export function getPartnerBySlug(slug: string): Partner | undefined {
  return PARTNERS.find((p) => p.slug === slug)
}

export function getActivePartners(): Partner[] {
  return PARTNERS.filter((p) => p.isActive)
}
