import type { Partner } from '@/types/partner'

export const PARTNERS: Partner[] = [
  {
    slug: 'ad-surgical',
    name: 'AD Surgical',
    vendorName: 'AD Surgical',
    type: 'brand',
    isActive: true,
    description: 'Leading provider of surgical sutures, wound closure, and procedure kits.',
    logo: {
      url: '/api/bunny/brands/ad-surgical.webp',
      altText: 'AD Surgical logo',
      width: 200,
      height: 80,
    },
    intro: 'AD Surgical is a trusted name in surgical wound management, offering a comprehensive portfolio of sutures, wound closure strips, staples, and procedure kits designed for clinical precision and consistent outcomes.',
    productCategories: ['surgical', 'wound-closure', 'sutures', 'procedure-kits'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'surgical', title: 'Surgical Supplies' },
      { handle: 'wound-care', title: 'Wound Care' },
    ],
    seoTitle: 'AD Surgical Products | MDSupplies',
    seoDescription: 'Shop AD Surgical sutures, wound closure, and procedure kits at wholesale prices through MDSupplies.',
  },
  {
    slug: 'cordx',
    name: 'CorDx',
    vendorName: 'CorDx',
    type: 'brand',
    isActive: true,
    description: 'Advanced rapid diagnostic testing solutions for clinical and point-of-care settings.',
    logo: {
      url: '/api/bunny/brands/cordx.png',
      altText: 'CorDx logo',
      width: 200,
      height: 80,
    },
    intro: 'CorDx develops rapid diagnostic tests and point-of-care solutions trusted by clinics, urgent care centers, and public health agencies. Their portfolio spans infectious disease testing, flu panels, and molecular assays.',
    productCategories: ['diagnostics', 'rapid-tests', 'point-of-care'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'diagnostics', title: 'Diagnostics' },
      { handle: 'rapid-tests', title: 'Rapid Tests' },
    ],
    seoTitle: 'CorDx Rapid Diagnostic Products | MDSupplies',
    seoDescription: 'Shop CorDx rapid diagnostic testing solutions at wholesale prices through MDSupplies.',
  },
  {
    slug: 'dukal',
    name: 'Dukal',
    vendorName: 'Dukal',
    type: 'brand',
    isActive: true,
    description: 'High-quality disposable medical products for wound care, exam, and procedure use.',
    logo: {
      url: '/api/bunny/brands/dukal.svg',
      altText: 'Dukal logo',
      width: 200,
      height: 80,
    },
    intro: 'Dukal Corporation manufactures high-quality disposable medical products including gauze sponges, wound dressings, exam gloves, and surgical drapes trusted by healthcare facilities across the United States.',
    productCategories: ['wound-care', 'surgical', 'exam-room', 'gauze'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'wound-care', title: 'Wound Care' },
      { handle: 'surgical', title: 'Surgical Supplies' },
      { handle: 'exam-room', title: 'Exam Room' },
    ],
    seoTitle: 'Dukal Medical Products | MDSupplies',
    seoDescription: 'Shop Dukal wound care, surgical, and disposable medical products at wholesale prices through MDSupplies.',
  },
  {
    slug: 'dynarex',
    name: 'Dynarex',
    vendorName: 'Dynarex',
    type: 'brand',
    isActive: true,
    description: 'Dependable general medical products trusted by healthcare providers nationwide.',
    logo: {
      url: '/api/bunny/brands/dynarex.png',
      altText: 'Dynarex logo',
      width: 200,
      height: 80,
    },
    intro: 'Dynarex is one of the largest manufacturers of general medical products in the United States, offering thousands of SKUs across gloves, wound care, personal protective equipment, and exam room essentials.',
    productCategories: ['disposables', 'wound-care', 'ppe', 'exam-room'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'disposables', title: 'Disposables' },
      { handle: 'ppe', title: 'PPE' },
      { handle: 'wound-care', title: 'Wound Care' },
    ],
    seoTitle: 'Dynarex Medical Products | MDSupplies',
    seoDescription: 'Shop Dynarex gloves, wound care, and disposable medical supplies at wholesale prices through MDSupplies.',
  },
  {
    slug: 'drive-medical',
    name: 'Drive Medical',
    vendorName: 'Drive Medical',
    type: 'brand',
    isActive: true,
    description: 'Durable medical equipment and mobility solutions for healthcare.',
    logo: {
      url: '/api/bunny/brands/drive-medical.svg',
      altText: 'Drive Medical logo',
      width: 200,
      height: 80,
    },
    intro: 'Drive Medical designs and manufactures durable medical equipment trusted by healthcare facilities and home health providers worldwide, including wheelchairs, walkers, and patient aids.',
    productCategories: ['dme', 'mobility-aids', 'home-health'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'dme', title: 'Durable Medical Equipment' },
      { handle: 'mobility-aids', title: 'Mobility Aids' },
    ],
    seoTitle: 'Drive Medical Products | MDSupplies',
    seoDescription: 'Shop Drive Medical durable medical equipment and mobility aids at wholesale prices.',
  },
  {
    slug: 'kadara',
    name: 'Kadara Medical',
    vendorName: 'Kadara',
    type: 'brand',
    isActive: true,
    description: 'Innovative medical supply solutions focused on quality and clinical performance.',
    logo: {
      url: '/api/bunny/brands/kadara.avif',
      altText: 'Kadara Medical logo',
      width: 200,
      height: 80,
    },
    intro: 'Kadara designs innovative medical supplies built for clinical performance and reliability. Their product line emphasizes quality manufacturing standards and consistent delivery for healthcare providers.',
    productCategories: ['medical-supplies', 'clinical-products'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'medical-supplies', title: 'Medical Supplies' },
    ],
    seoTitle: 'Kadara Medical Supply Products | MDSupplies',
    seoDescription: 'Shop Kadara innovative medical supply solutions at wholesale prices through MDSupplies.',
  },
  {
    slug: 'kemp-usa',
    name: 'Kemp USA',
    vendorName: 'Kemp USA',
    type: 'brand',
    isActive: true,
    description: 'Professional-grade medical equipment and emergency response supplies.',
    logo: {
      url: '/api/bunny/brands/kemp-usa.svg',
      altText: 'Kemp USA logo',
      width: 200,
      height: 80,
    },
    intro: 'Kemp USA manufactures professional-grade medical and emergency response equipment including stretchers, backboards, first aid kits, and AED supplies used by first responders and healthcare facilities.',
    productCategories: ['emergency', 'first-aid', 'stretchers', 'aed'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'emergency', title: 'Emergency Supplies' },
      { handle: 'first-aid', title: 'First Aid' },
    ],
    seoTitle: 'Kemp USA Emergency & Medical Equipment | MDSupplies',
    seoDescription: 'Shop Kemp USA medical equipment and emergency response supplies at wholesale prices through MDSupplies.',
  },
  {
    slug: 'graham-field',
    name: 'Graham Field',
    vendorName: 'Graham Field',
    type: 'brand',
    isActive: true,
    description: 'Comprehensive durable medical equipment and rehabilitation solutions.',
    logo: {
      url: '/api/bunny/brands/graham-field.svg',
      altText: 'Graham Field logo',
      width: 200,
      height: 80,
    },
    intro: 'Graham Field Health Products is a leading manufacturer and distributor of durable medical equipment and rehabilitation products. Their brands—including Lumex and Everest & Jennings—serve patients from acute care to home health settings.',
    productCategories: ['dme', 'rehabilitation', 'patient-care', 'mobility-aids'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'dme', title: 'Durable Medical Equipment' },
      { handle: 'rehabilitation', title: 'Rehabilitation' },
    ],
    seoTitle: 'Graham Field Medical Products | MDSupplies',
    seoDescription: 'Shop Graham Field durable medical equipment and rehabilitation solutions at wholesale prices through MDSupplies.',
  },
  {
    slug: 'truecare',
    name: 'TrueCare Biomedix',
    vendorName: 'TrueCare',
    type: 'brand',
    isActive: true,
    description: 'Patient-centered wound care and disposable medical supply solutions.',
    logo: {
      url: '/api/bunny/brands/truecare.svg',
      altText: 'TrueCare Biomedix logo',
      width: 200,
      height: 80,
    },
    intro: 'TrueCare develops patient-centered wound care and disposable medical supplies that prioritize comfort and clinical effectiveness. Their products are designed for consistent performance in wound management and daily patient care.',
    productCategories: ['wound-care', 'disposables', 'patient-care'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'wound-care', title: 'Wound Care' },
      { handle: 'disposables', title: 'Disposables' },
    ],
    seoTitle: 'TrueCare Wound Care & Disposable Supplies | MDSupplies',
    seoDescription: 'Shop TrueCare wound care and disposable medical supply solutions at wholesale prices through MDSupplies.',
  },
  {
    slug: 'dawn-mist',
    name: 'Dawn Mist',
    vendorName: 'Dawn Mist',
    type: 'brand',
    isActive: true,
    description: 'Premium personal care and hygiene products for healthcare facilities.',
    logo: {
      url: '/api/bunny/brands/dawn-mist.avif',
      altText: 'Dawn Mist logo',
      width: 200,
      height: 80,
    },
    intro: 'Dawn Mist is a leading brand of personal care products trusted by hospitals and long-term care facilities across North America.',
    productCategories: ['personal-care', 'hygiene', 'bath-supplies'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'personal-care', title: 'Personal Care' },
      { handle: 'hygiene', title: 'Hygiene Supplies' },
    ],
    seoTitle: 'Dawn Mist Products | MDSupplies',
    seoDescription: 'Browse Dawn Mist personal care and hygiene products available at wholesale prices through MDSupplies.',
  },
  {
    slug: 'lumex',
    name: 'Lumex',
    vendorName: 'Lumex',
    type: 'brand',
    isActive: true,
    description: 'Durable medical equipment and mobility aids for patient care.',
    logo: {
      url: '/api/bunny/brands/lumex.svg',
      altText: 'Lumex logo',
      width: 200,
      height: 80,
    },
    intro: 'Lumex specializes in durable medical equipment including walkers, wheelchairs, and patient lifts used in home care and clinical settings.',
    productCategories: ['dme', 'mobility-aids', 'patient-lifts'],
    featuredProducts: [],
    relatedCategories: [
      { handle: 'dme', title: 'Durable Medical Equipment' },
      { handle: 'mobility-aids', title: 'Mobility Aids' },
    ],
  },
]

export function getPartnerBySlug(slug: string): Partner | undefined {
  return PARTNERS.find((p) => p.slug === slug)
}

export function getActivePartners(): Partner[] {
  return PARTNERS.filter((p) => p.isActive)
}
