export const ROUTES = {
  home: '/',
  categories: '/categories',
  category: (slug: string) => `/category/${slug}`,
  subcategory: (cat: string, sub: string) => `/category/${cat}/${sub}`,
  product: (slug: string) => `/product/${slug}`,
  partners: '/partners',
  partner: (slug: string) => `/partners/${slug}`,
  brands: '/brands',
  brand: (slug: string) => `/brands/${slug}`,
  industries: '/industries',
  industry: (slug: string) => `/industries/${slug}`,
  solutions: { occ: '/solutions/occ' },
  blog: '/blog',
  article: (slug: string) => `/blog/${slug}`,
  search: '/search',
  cart: '/cart',
  account: '/account',
  accountLogin: '/account/login',
  accountOrders: '/account/orders',
  contact: '/contact',
  returns: '/returns',
  policy: (slug: string) => `/policies/${slug}`,
  about: '/about',
  faq: '/faq',
} as const
